# -*- coding: utf-8 -*-
"""Bay of Bengal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-MOKMUtatiM_u6dyIrM4bOrnkTs0Yy-
"""

pip install argopy